manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: em
      url-base: https://github.com/ecstatic-morse
  projects:
    - name: zmk
      remote: urob
      revision: going-modular
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-tri-state
      remote: urob
      revision: main
    - name: zmk
      remote: em
      revision: molock
  selfs:
    path: config