manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ldebritto
      url-base: https://github.com/ldebritto
  projects:
    - name: zmk
      remote: ldebritto
      revision: main
      import: app/west.yml
  self:
    path: config